[package]
name = "rust-aoc"
version = "0.1.0"
authors = ["Jacob Newman"]
edition = "2021"

[lib]
bench = false

[dev-dependencies]
criterion = { version = "0.5.1" }

[[bench]]
name = "aoc-timer"
harness = false

[dependencies]
aoc-util = { path = "../aoc-util" }
itertools = "0.13.0"